default_language_version:
  python: python3
repos:
  - repo: https://github.com/jorisroovers/gitlint.git
    rev: v0.19.1
    hooks:
      - id: gitlint

  - repo: https://github.com/ambv/black.git
    rev: 24.1.1
    hooks:
      - id: black
        language_version: python3
        additional_dependencies: ['click==8.0.4']

  - repo: https://github.com/pycqa/flake8.git
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]

  - repo: https://github.com/pycqa/isort.git
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
